### ISSUE TITLE
Can it be used for mobile of LncRNA

### ISSUE THREAD

**Issue by zhangwenda0518** [bioc/mobileRNA#1]
I am studying a grafting species and I want to further explore the mobile of LncRNA between rootstock and scion. Can your tool be used for its analysis? How can I use it? 
Thank you！

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of Bioconductor, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
